//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlpsMountains
    {
        public int Id { get; set; }
        public Nullable<int> Alp_Id { get; set; }
        public Nullable<int> Mountain_Id { get; set; }
    
        public virtual Alp Alp { get; set; }
        public virtual Mountain Mountain { get; set; }
    }
}
